bectl apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-client
  namespace: {{ .Values.namespace.main.name }}
spec:
  # tls:
  #   - hosts:
  #     - {{ .Values.ingress.host }}
  #     # This assumes tls-secret exists and the SSL
  #     # certificate contains a CN for foo.bar.com
  #     secretName: k8sengineers-tls
  ingressClassName: nginx
  rules:
  # Use the host you used in your kubernetes Ingress Configurations
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path.client }}
        pathType: Prefix
        backend:
          service:
           name: {{ .Release.Name }}-{{ .Chart.Name }}-client
           port: 
             number: 4200

# installation guide: https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
# kubectl port-forward --namespace=ingress-nginx service/ingress-nginx-controller 8080:80
#curl --resolve example.com:8080:127.0.0.1 http://example.com:8080