apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-main
  namespace: {{ .Values.namespace.main.name }}
  labels: 
    app: {{ .Release.Name }}-{{ .Chart.Name }}-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-main
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-main
        image: {{ .Values.image.main.repository }}:{{ .Values.image.main.tag }}
        imagePullPolicy: Always
        ports:
        - name: enodeapi-port
          containerPort: 5000
        env: 
         - name: MONGOURI
           value: 'mongodb://emongo:27017/epoc'
         - name: SECRETORKEY
           value: 'k1234e6s78h9av'
      # imagePullSecrets:
      # - name: regcred 
     
