apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-books
  namespace: {{ .Values.namespace.main.name }}
spec:
  ports:
  - port: {{ .Values.service.books.port }}
    targetPort: ebooksapi-port
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-books
  type: {{ .Values.service.books.type }}