---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-pvc
  namespace: {{ .Values.namespace.main.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-sc
  resources:
    requests:
      storage: 500Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-sc
  namespace: {{ .Values.namespace.main.name }}
provisioner: kubernetes.io/host-path
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-pv
  namespace: {{ .Values.namespace.main.name }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-sc
  hostPath:
    path: /data/db