apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-dbsecret
  namespace: {{ .Values.namespace.main.name }}
type: Opaque
data:
  mysqldb-pass: ZW1hcnRkYnBhc3M= 
  rmq-pass: Z3Vlc3Q=
